---
- name: Enable EPEL-Repo for Redhat and CentOS
  package:
    name: epel-release
    state: present
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" and ansible_distribution != "Fedora")
  tags:
    - common
    - epel
    - repository

- name: Enable RPM Fusion for Fedora
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: (ansible_os_family == "RedHat" and ansible_distribution == "Fedora")
  tags:
    - common
    - rpmfusion
    - repository
